name: Deploy Assets

on:
  push:
    tags:
      - "v*" # Matches tags starting with "v", e.g., "v1.0.0"
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          protocol: ftps
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: static-resources/
          server-dir: /public_html/resources/v2024/
